global:
  scrape_interval: 3s
  evaluation_interval: 3s

scrape_configs:
  - job_name: 'room-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['room-service:8080']

  - job_name: 'booking-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['booking-service:8081']

  - job_name: 'customer-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['customer-service:8082']

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8083']